// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCredentialAccount = `-- name: CreateCredentialAccount :one
INSERT INTO
    account (provider, id, account_id, user_id, "password")
values
    ('credential', $1, $2, $3, $4)
RETURNING
    created_at
`

type CreateCredentialAccountParams struct {
	ID        string
	AccountID string
	UserID    string
	Password  *string
}

func (q *Queries) CreateCredentialAccount(ctx context.Context, arg CreateCredentialAccountParams) (pgtype.Timestamp, error) {
	row := q.db.QueryRow(ctx, createCredentialAccount,
		arg.ID,
		arg.AccountID,
		arg.UserID,
		arg.Password,
	)
	var created_at pgtype.Timestamp
	err := row.Scan(&created_at)
	return created_at, err
}

const createRefreshToken = `-- name: CreateRefreshToken :exec
insert into
    refresh_tokens (id, user_id, token_hash, valid_window, device_id)
values
    ($1, $2, $3, $4, $5)
`

type CreateRefreshTokenParams struct {
	ID          string
	UserID      string
	TokenHash   string
	ValidWindow string
	DeviceID    string
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, createRefreshToken,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.ValidWindow,
		arg.DeviceID,
	)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO
    "user" (id, name, email, image)
values
    ($1, $2, $3, $4)
RETURNING
    created_at
`

type CreateUserParams struct {
	ID    string
	Name  string
	Email string
	Image *string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (pgtype.Timestamp, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Image,
	)
	var created_at pgtype.Timestamp
	err := row.Scan(&created_at)
	return created_at, err
}

const createVerification = `-- name: CreateVerification :exec
insert into
    verifications (
        id,
        user_id,
        token,
        valid_window,
        "type",
        ip,
        callback_url
    )
values
    ($1, $2, $3, $4, $5, $6, $7)
`

type CreateVerificationParams struct {
	ID          string
	UserID      string
	Token       string
	ValidWindow string
	Type        VerificationType
	Ip          string
	CallbackUrl *string
}

func (q *Queries) CreateVerification(ctx context.Context, arg CreateVerificationParams) error {
	_, err := q.db.Exec(ctx, createVerification,
		arg.ID,
		arg.UserID,
		arg.Token,
		arg.ValidWindow,
		arg.Type,
		arg.Ip,
		arg.CallbackUrl,
	)
	return err
}

const credentialAccountExistsByIdentifier = `-- name: CredentialAccountExistsByIdentifier :one
select
    exists (
        select
            1
        from
            account
        where
            provider = 'credential'
            and account_id = $1
    )
`

func (q *Queries) CredentialAccountExistsByIdentifier(ctx context.Context, accountID string) (bool, error) {
	row := q.db.QueryRow(ctx, credentialAccountExistsByIdentifier, accountID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const findCredentialAccountById = `-- name: FindCredentialAccountById :one
SELECT
    id, account_id, provider, user_id, access_token, refresh_token, id_token, access_token_expires_at, refresh_token_expires_at, scope, password, created_at, updated_at
FROM
    account
where
    provider = 'credential'
    and account_id = $1
limit
    1
`

func (q *Queries) FindCredentialAccountById(ctx context.Context, accountID string) (Account, error) {
	row := q.db.QueryRow(ctx, findCredentialAccountById, accountID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Provider,
		&i.UserID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.IDToken,
		&i.AccessTokenExpiresAt,
		&i.RefreshTokenExpiresAt,
		&i.Scope,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT
    id, name, email, email_verified, image, created_at, updated_at, prefs
FROM
    "user"
where
    email = $1
limit
    1
`

func (q *Queries) FindUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, findUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Image,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Prefs,
	)
	return i, err
}

const findUserById = `-- name: FindUserById :one
SELECT
    id, name, email, email_verified, image, created_at, updated_at, prefs
FROM
    "user"
where
    id = $1
limit
    1
`

func (q *Queries) FindUserById(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, findUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Image,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Prefs,
	)
	return i, err
}

const getPrimedVerificationByToken = `-- name: GetPrimedVerificationByToken :one
select
    v.id, v.user_id, v.token, v.type, v.valid_window, v.created_at, v.used_at, v.status, v.used, v.ip, v.callback_url,
    (created_at + valid_window)::timestamptz as expires_at
from
    verifications v
where
    v.token = $1
    and v.status = 'primed'
    and v.used_at is null
    and (v.created_at + v.valid_window) <= now()
limit
    1
`

type GetPrimedVerificationByTokenRow struct {
	ID          string
	UserID      string
	Token       string
	Type        VerificationType
	ValidWindow string
	CreatedAt   pgtype.Timestamptz
	UsedAt      pgtype.Timestamptz
	Status      *VerificationStatus
	Used        *bool
	Ip          string
	CallbackUrl *string
	ExpiresAt   pgtype.Timestamptz
}

func (q *Queries) GetPrimedVerificationByToken(ctx context.Context, token string) (GetPrimedVerificationByTokenRow, error) {
	row := q.db.QueryRow(ctx, getPrimedVerificationByToken, token)
	var i GetPrimedVerificationByTokenRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.Type,
		&i.ValidWindow,
		&i.CreatedAt,
		&i.UsedAt,
		&i.Status,
		&i.Used,
		&i.Ip,
		&i.CallbackUrl,
		&i.ExpiresAt,
	)
	return i, err
}

const getUnusedVerificationByToken = `-- name: GetUnusedVerificationByToken :one
select
    v.id, v.user_id, v.token, v.type, v.valid_window, v.created_at, v.used_at, v.status, v.used, v.ip, v.callback_url,
    (created_at + valid_window)::timestamptz as expires_at
from
    verifications v
where
    v.token = $1
    and v.used = false
    and (v.created_at + v.valid_window) <= now()
limit
    1
`

type GetUnusedVerificationByTokenRow struct {
	ID          string
	UserID      string
	Token       string
	Type        VerificationType
	ValidWindow string
	CreatedAt   pgtype.Timestamptz
	UsedAt      pgtype.Timestamptz
	Status      *VerificationStatus
	Used        *bool
	Ip          string
	CallbackUrl *string
	ExpiresAt   pgtype.Timestamptz
}

func (q *Queries) GetUnusedVerificationByToken(ctx context.Context, token string) (GetUnusedVerificationByTokenRow, error) {
	row := q.db.QueryRow(ctx, getUnusedVerificationByToken, token)
	var i GetUnusedVerificationByTokenRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.Type,
		&i.ValidWindow,
		&i.CreatedAt,
		&i.UsedAt,
		&i.Status,
		&i.Used,
		&i.Ip,
		&i.CallbackUrl,
		&i.ExpiresAt,
	)
	return i, err
}

const invalidateRefreshTokensForDevice = `-- name: InvalidateRefreshTokensForDevice :exec
update refresh_tokens
set
    revoked_at = now()
where
    device_id = $1
    and revoked_at is null
`

func (q *Queries) InvalidateRefreshTokensForDevice(ctx context.Context, deviceID string) error {
	_, err := q.db.Exec(ctx, invalidateRefreshTokensForDevice, deviceID)
	return err
}

const isEmailAvailable = `-- name: IsEmailAvailable :one
select
    not exists (
        select
            1
        from
            "user"
        where
            email = $1
    )
`

func (q *Queries) IsEmailAvailable(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, isEmailAvailable, email)
	var not_exists bool
	err := row.Scan(&not_exists)
	return not_exists, err
}

const listUnusedVerificationsByUser = `-- name: ListUnusedVerificationsByUser :many
select
    id,
    token,
    "type",
    (created_at + valid_window)::timestamptz as expires_at
from
    verifications
where
    user_id = $1
    and used = false
`

type ListUnusedVerificationsByUserRow struct {
	ID        string
	Token     string
	Type      VerificationType
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) ListUnusedVerificationsByUser(ctx context.Context, userID string) ([]ListUnusedVerificationsByUserRow, error) {
	rows, err := q.db.Query(ctx, listUnusedVerificationsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnusedVerificationsByUserRow
	for rows.Next() {
		var i ListUnusedVerificationsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Token,
			&i.Type,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupRefreshTokenByDevice = `-- name: LookupRefreshTokenByDevice :one
select
    rts.user_id,
    rts.usable
from
    refresh_token_states rts
where
    rts.device_id = $1
    and token_hash = $2
limit
    1
`

type LookupRefreshTokenByDeviceParams struct {
	DeviceID  string
	TokenHash string
}

type LookupRefreshTokenByDeviceRow struct {
	UserID string
	Usable *bool
}

func (q *Queries) LookupRefreshTokenByDevice(ctx context.Context, arg LookupRefreshTokenByDeviceParams) (LookupRefreshTokenByDeviceRow, error) {
	row := q.db.QueryRow(ctx, lookupRefreshTokenByDevice, arg.DeviceID, arg.TokenHash)
	var i LookupRefreshTokenByDeviceRow
	err := row.Scan(&i.UserID, &i.Usable)
	return i, err
}

const markVerificationUsed = `-- name: MarkVerificationUsed :exec
update verifications
set
    used_at = now()
where
    token = $1
`

func (q *Queries) MarkVerificationUsed(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, markVerificationUsed, token)
	return err
}

const primeVerification = `-- name: PrimeVerification :exec
update verifications
set
    status = 'primed'
where
    token = $1
`

func (q *Queries) PrimeVerification(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, primeVerification, token)
	return err
}

const removeStaleRefreshTokens = `-- name: RemoveStaleRefreshTokens :exec
delete from refresh_tokens
where
    revoked_at is not null
    or (created_at + valid_window) < now()
`

func (q *Queries) RemoveStaleRefreshTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, removeStaleRefreshTokens)
	return err
}

const setUserCredentialPassword = `-- name: SetUserCredentialPassword :exec
update account
set
    "password" = $1,
    updated_at = now()
where
    provider = 'credential'
    and user_id = $2
`

type SetUserCredentialPasswordParams struct {
	Password *string
	UserID   string
}

func (q *Queries) SetUserCredentialPassword(ctx context.Context, arg SetUserCredentialPasswordParams) error {
	_, err := q.db.Exec(ctx, setUserCredentialPassword, arg.Password, arg.UserID)
	return err
}

const unusedVerificationExistsByToken = `-- name: UnusedVerificationExistsByToken :one
select
    exists (
        select
            1
        from
            verifications
        where
            token = $1
            and not used
            and ((created_at + valid_window) < now())
    )
`

func (q *Queries) UnusedVerificationExistsByToken(ctx context.Context, token string) (bool, error) {
	row := q.db.QueryRow(ctx, unusedVerificationExistsByToken, token)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const userExistsWithId = `-- name: UserExistsWithId :one
select
    exists (
        select
            1
        from
            "user"
        where
            id = $1
    )
`

func (q *Queries) UserExistsWithId(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, userExistsWithId, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const verifyUserEmail = `-- name: VerifyUserEmail :exec
update "user"
set
    email_verified = true,
    updated_at = now()
where
    id = $1
`

func (q *Queries) VerifyUserEmail(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, verifyUserEmail, id)
	return err
}
