// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCredentialAccount = `-- name: CreateCredentialAccount :one
INSERT INTO
    account (provider, id, account_id, user_id, "password")
VALUES
    ('credential', $1, $2, $3, $4)
RETURNING
    created_at
`

type CreateCredentialAccountParams struct {
	ID        string
	AccountID string
	UserID    string
	Password  *string
}

func (q *Queries) CreateCredentialAccount(ctx context.Context, arg CreateCredentialAccountParams) (pgtype.Timestamp, error) {
	row := q.db.QueryRow(ctx, createCredentialAccount,
		arg.ID,
		arg.AccountID,
		arg.UserID,
		arg.Password,
	)
	var created_at pgtype.Timestamp
	err := row.Scan(&created_at)
	return created_at, err
}

const createRefreshToken = `-- name: CreateRefreshToken :exec
insert into
    refresh_tokens (id, user_id, token_hash, valid_window, device_id)
values
    ($1, $2, $3, $4, $5)
`

type CreateRefreshTokenParams struct {
	ID          string
	UserID      string
	TokenHash   string
	ValidWindow string
	DeviceID    string
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, createRefreshToken,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.ValidWindow,
		arg.DeviceID,
	)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO
    "user" (id, name, email, image)
VALUES
    ($1, $2, $3, $4)
RETURNING
    created_at
`

type CreateUserParams struct {
	ID    string
	Name  string
	Email string
	Image *string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (pgtype.Timestamp, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Image,
	)
	var created_at pgtype.Timestamp
	err := row.Scan(&created_at)
	return created_at, err
}

const credentialAccountExistsByIdentifier = `-- name: CredentialAccountExistsByIdentifier :one
select
    exists (
        select
            1
        from
            account
        where
            provider = 'credential'
            and account_id = $1
    )
`

func (q *Queries) CredentialAccountExistsByIdentifier(ctx context.Context, accountID string) (bool, error) {
	row := q.db.QueryRow(ctx, credentialAccountExistsByIdentifier, accountID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const findCredentialAccountById = `-- name: FindCredentialAccountById :one
SELECT
    id, account_id, provider, user_id, access_token, refresh_token, id_token, access_token_expires_at, refresh_token_expires_at, scope, password, created_at, updated_at
FROM
    account
WHERE
    provider = 'credential'
    and account_id = $1
limit
    1
`

func (q *Queries) FindCredentialAccountById(ctx context.Context, accountID string) (Account, error) {
	row := q.db.QueryRow(ctx, findCredentialAccountById, accountID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Provider,
		&i.UserID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.IDToken,
		&i.AccessTokenExpiresAt,
		&i.RefreshTokenExpiresAt,
		&i.Scope,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT
    id, name, email, email_verified, image, created_at, updated_at, prefs
FROM
    "user"
WHERE
    email = $1
LIMIT
    1
`

func (q *Queries) FindUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, findUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Image,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Prefs,
	)
	return i, err
}

const findUserById = `-- name: FindUserById :one
SELECT
    id, name, email, email_verified, image, created_at, updated_at, prefs
FROM
    "user"
WHERE
    id = $1
LIMIT
    1
`

func (q *Queries) FindUserById(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, findUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Image,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Prefs,
	)
	return i, err
}

const invalidateRefreshTokensForDevice = `-- name: InvalidateRefreshTokensForDevice :exec
update refresh_tokens
set
    revoked_at = now()
where
    device_id = $1
    and revoked_at is null
`

func (q *Queries) InvalidateRefreshTokensForDevice(ctx context.Context, deviceID string) error {
	_, err := q.db.Exec(ctx, invalidateRefreshTokensForDevice, deviceID)
	return err
}

const isEmailAvailable = `-- name: IsEmailAvailable :one
select
    not exists (
        select
            1
        from
            "user"
        where
            email = $1
    )
`

func (q *Queries) IsEmailAvailable(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, isEmailAvailable, email)
	var not_exists bool
	err := row.Scan(&not_exists)
	return not_exists, err
}

const lookupRefreshTokenByDevice = `-- name: LookupRefreshTokenByDevice :one
select
    rts.user_id,
    rts.usable
from
    refresh_token_states rts
where
    rts.device_id = $1
    and token_hash = $2
limit
    1
`

type LookupRefreshTokenByDeviceParams struct {
	DeviceID  string
	TokenHash string
}

type LookupRefreshTokenByDeviceRow struct {
	UserID string
	Usable *bool
}

func (q *Queries) LookupRefreshTokenByDevice(ctx context.Context, arg LookupRefreshTokenByDeviceParams) (LookupRefreshTokenByDeviceRow, error) {
	row := q.db.QueryRow(ctx, lookupRefreshTokenByDevice, arg.DeviceID, arg.TokenHash)
	var i LookupRefreshTokenByDeviceRow
	err := row.Scan(&i.UserID, &i.Usable)
	return i, err
}

const removeStaleRefreshTokens = `-- name: RemoveStaleRefreshTokens :exec
delete from refresh_tokens
where
    revoked_at is not null
    or (created_at + valid_window) < now()
`

func (q *Queries) RemoveStaleRefreshTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, removeStaleRefreshTokens)
	return err
}
