// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: kyc.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createKycRecord = `-- name: CreateKycRecord :exec
insert into
    kyc_records (
        id,
        valid_window,
        identity_doc,
        proof_of_address,
        user_id
    )
values
    ($1, $2, $3, $4, $5)
`

type CreateKycRecordParams struct {
	ID             string
	ValidWindow    string
	IdentityDoc    []byte
	ProofOfAddress []byte
	UserID         *string
}

func (q *Queries) CreateKycRecord(ctx context.Context, arg CreateKycRecordParams) error {
	_, err := q.db.Exec(ctx, createKycRecord,
		arg.ID,
		arg.ValidWindow,
		arg.IdentityDoc,
		arg.ProofOfAddress,
		arg.UserID,
	)
	return err
}

const getKycRecordByUser = `-- name: GetKycRecordByUser :one
select
    id, user_id, status, risk_profile, verified_at, valid_window, identity_doc, proof_of_address, created_at, updated_at, verified_by, rejection_reason
from
    kyc_records
where
    user_id = $1
limit
    1
`

func (q *Queries) GetKycRecordByUser(ctx context.Context, userID *string) (KycRecord, error) {
	row := q.db.QueryRow(ctx, getKycRecordByUser, userID)
	var i KycRecord
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.RiskProfile,
		&i.VerifiedAt,
		&i.ValidWindow,
		&i.IdentityDoc,
		&i.ProofOfAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VerifiedBy,
		&i.RejectionReason,
	)
	return i, err
}

const listKycs = `-- name: ListKycs :many
select
    k.id, k.user_id, k.status, k.risk_profile, k.verified_at, k.valid_window, k.identity_doc, k.proof_of_address, k.created_at, k.updated_at, k.verified_by, k.rejection_reason,
    (k.created_at + k.valid_window) <= now()
    or k.status not in ('rejected', 'expired')::boolean as usable
from
    kyc_records k
`

type ListKycsRow struct {
	ID              string
	UserID          *string
	Status          KycStatus
	RiskProfile     KycRiskProfile
	VerifiedAt      pgtype.Timestamptz
	ValidWindow     string
	IdentityDoc     []byte
	ProofOfAddress  []byte
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	VerifiedBy      *string
	RejectionReason *string
	Usable          *bool
}

func (q *Queries) ListKycs(ctx context.Context) ([]ListKycsRow, error) {
	rows, err := q.db.Query(ctx, listKycs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListKycsRow
	for rows.Next() {
		var i ListKycsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.RiskProfile,
			&i.VerifiedAt,
			&i.ValidWindow,
			&i.IdentityDoc,
			&i.ProofOfAddress,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VerifiedBy,
			&i.RejectionReason,
			&i.Usable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKycsByRiskProfile = `-- name: ListKycsByRiskProfile :many
select
    k.id, k.user_id, k.status, k.risk_profile, k.verified_at, k.valid_window, k.identity_doc, k.proof_of_address, k.created_at, k.updated_at, k.verified_by, k.rejection_reason,
    (k.created_at + k.valid_window)::timestamptz as expires_at,
    (k.created_at + k.valid_window) <= now()
    or k.status not in ('rejected', 'expired')::boolean as usable
from
    kyc_records k
where
    k.risk_profile = $1
order by
    verified_at desc
`

type ListKycsByRiskProfileRow struct {
	ID              string
	UserID          *string
	Status          KycStatus
	RiskProfile     KycRiskProfile
	VerifiedAt      pgtype.Timestamptz
	ValidWindow     string
	IdentityDoc     []byte
	ProofOfAddress  []byte
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	VerifiedBy      *string
	RejectionReason *string
	ExpiresAt       pgtype.Timestamptz
	Usable          *bool
}

func (q *Queries) ListKycsByRiskProfile(ctx context.Context, riskProfile KycRiskProfile) ([]ListKycsByRiskProfileRow, error) {
	rows, err := q.db.Query(ctx, listKycsByRiskProfile, riskProfile)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListKycsByRiskProfileRow
	for rows.Next() {
		var i ListKycsByRiskProfileRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.RiskProfile,
			&i.VerifiedAt,
			&i.ValidWindow,
			&i.IdentityDoc,
			&i.ProofOfAddress,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VerifiedBy,
			&i.RejectionReason,
			&i.ExpiresAt,
			&i.Usable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setKycStatus = `-- name: SetKycStatus :exec
update kyc_records
set
    updated_at = now(),
    status = $2
where
    user_id = $1
`

type SetKycStatusParams struct {
	UserID *string
	Status KycStatus
}

func (q *Queries) SetKycStatus(ctx context.Context, arg SetKycStatusParams) error {
	_, err := q.db.Exec(ctx, setKycStatus, arg.UserID, arg.Status)
	return err
}

const updateKycDocuments = `-- name: UpdateKycDocuments :exec
update kyc_records
set
    updated_at = now(),
    identity_doc = $1,
    proof_of_address = $2
where
    user_id = $1
`

type UpdateKycDocumentsParams struct {
	IdentityDoc    []byte
	ProofOfAddress []byte
}

func (q *Queries) UpdateKycDocuments(ctx context.Context, arg UpdateKycDocumentsParams) error {
	_, err := q.db.Exec(ctx, updateKycDocuments, arg.IdentityDoc, arg.ProofOfAddress)
	return err
}
