// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: kyc.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createKycRecord = `-- name: CreateKycRecord :exec
insert into
    kyc_records (
        id,
        valid_window,
        identity_doc,
        proof_of_address,
        user_id
    )
values
    ($1, $2, $3, $4, $5)
`

type CreateKycRecordParams struct {
	ID             string
	ValidWindow    string
	IdentityDoc    []byte
	ProofOfAddress []byte
	UserID         *string
}

func (q *Queries) CreateKycRecord(ctx context.Context, arg CreateKycRecordParams) error {
	_, err := q.db.Exec(ctx, createKycRecord,
		arg.ID,
		arg.ValidWindow,
		arg.IdentityDoc,
		arg.ProofOfAddress,
		arg.UserID,
	)
	return err
}

const getKycRecordByUser = `-- name: GetKycRecordByUser :one
select
    k.id, k.user_id, k.status, k.risk_profile, k.verified_at, k.valid_window, k.identity_doc, k.proof_of_address, k.created_at, k.updated_at, k.verified_by, k.rejection_reason,
    (k.created_at + k.valid_window)::timestamptz as expires_at,
    coalesce(
        k.status = 'verified'
        and now() <= (k.created_at + k.valid_window),
        false
    )::boolean as usable
from
    kyc_records k
where
    k.user_id = $1
limit
    1
`

type GetKycRecordByUserRow struct {
	ID              string
	UserID          *string
	Status          KycStatus
	RiskProfile     KycRiskProfile
	VerifiedAt      pgtype.Timestamptz
	ValidWindow     string
	IdentityDoc     []byte
	ProofOfAddress  []byte
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	VerifiedBy      *string
	RejectionReason *string
	ExpiresAt       pgtype.Timestamptz
	Usable          bool
}

func (q *Queries) GetKycRecordByUser(ctx context.Context, userID *string) (GetKycRecordByUserRow, error) {
	row := q.db.QueryRow(ctx, getKycRecordByUser, userID)
	var i GetKycRecordByUserRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.RiskProfile,
		&i.VerifiedAt,
		&i.ValidWindow,
		&i.IdentityDoc,
		&i.ProofOfAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VerifiedBy,
		&i.RejectionReason,
		&i.ExpiresAt,
		&i.Usable,
	)
	return i, err
}

const listKycs = `-- name: ListKycs :many
select
    k.id, k.user_id, k.status, k.risk_profile, k.verified_at, k.valid_window, k.identity_doc, k.proof_of_address, k.created_at, k.updated_at, k.verified_by, k.rejection_reason,
    (k.created_at + k.valid_window)::timestamptz as expires_at,
    coalesce(
        k.status = 'verified'
        and now() <= (k.created_at + k.valid_window),
        false
    )::boolean as usable
from
    kyc_records k
order by
    created_at desc
`

type ListKycsRow struct {
	ID              string
	UserID          *string
	Status          KycStatus
	RiskProfile     KycRiskProfile
	VerifiedAt      pgtype.Timestamptz
	ValidWindow     string
	IdentityDoc     []byte
	ProofOfAddress  []byte
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	VerifiedBy      *string
	RejectionReason *string
	ExpiresAt       pgtype.Timestamptz
	Usable          bool
}

func (q *Queries) ListKycs(ctx context.Context) ([]ListKycsRow, error) {
	rows, err := q.db.Query(ctx, listKycs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListKycsRow
	for rows.Next() {
		var i ListKycsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.RiskProfile,
			&i.VerifiedAt,
			&i.ValidWindow,
			&i.IdentityDoc,
			&i.ProofOfAddress,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VerifiedBy,
			&i.RejectionReason,
			&i.ExpiresAt,
			&i.Usable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKycsByRiskProfile = `-- name: ListKycsByRiskProfile :many
select
    k.id, k.user_id, k.status, k.risk_profile, k.verified_at, k.valid_window, k.identity_doc, k.proof_of_address, k.created_at, k.updated_at, k.verified_by, k.rejection_reason,
    (k.created_at + k.valid_window)::timestamptz as expires_at,
    coalesce(
        k.status = 'verified'
        and now() <= (k.created_at + k.valid_window),
        false
    )::boolean as usable
from
    kyc_records k
where
    k.risk_profile = $1
order by
    verified_at desc nulls last
`

type ListKycsByRiskProfileRow struct {
	ID              string
	UserID          *string
	Status          KycStatus
	RiskProfile     KycRiskProfile
	VerifiedAt      pgtype.Timestamptz
	ValidWindow     string
	IdentityDoc     []byte
	ProofOfAddress  []byte
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	VerifiedBy      *string
	RejectionReason *string
	ExpiresAt       pgtype.Timestamptz
	Usable          bool
}

func (q *Queries) ListKycsByRiskProfile(ctx context.Context, riskProfile KycRiskProfile) ([]ListKycsByRiskProfileRow, error) {
	rows, err := q.db.Query(ctx, listKycsByRiskProfile, riskProfile)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListKycsByRiskProfileRow
	for rows.Next() {
		var i ListKycsByRiskProfileRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.RiskProfile,
			&i.VerifiedAt,
			&i.ValidWindow,
			&i.IdentityDoc,
			&i.ProofOfAddress,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VerifiedBy,
			&i.RejectionReason,
			&i.ExpiresAt,
			&i.Usable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markKycVerifying = `-- name: MarkKycVerifying :exec
update kyc_records
set
    updated_at = now(),
    status = 'verifying'
where
    user_id = $1
    and status in ('pending', 'rejected', 'expired')
`

func (q *Queries) MarkKycVerifying(ctx context.Context, userID *string) error {
	_, err := q.db.Exec(ctx, markKycVerifying, userID)
	return err
}

const rejectKyc = `-- name: RejectKyc :exec
update kyc_records
set
    updated_at = now(),
    status = 'rejected',
    verified_by = $2,
    rejection_reason = $3,
    verified_at = null
where
    user_id = $1
`

type RejectKycParams struct {
	UserID          *string
	VerifiedBy      *string
	RejectionReason *string
}

func (q *Queries) RejectKyc(ctx context.Context, arg RejectKycParams) error {
	_, err := q.db.Exec(ctx, rejectKyc, arg.UserID, arg.VerifiedBy, arg.RejectionReason)
	return err
}

const setKycStatus = `-- name: SetKycStatus :exec
update kyc_records
set
    updated_at = now(),
    status = $2
where
    user_id = $1
`

type SetKycStatusParams struct {
	UserID *string
	Status KycStatus
}

func (q *Queries) SetKycStatus(ctx context.Context, arg SetKycStatusParams) error {
	_, err := q.db.Exec(ctx, setKycStatus, arg.UserID, arg.Status)
	return err
}

const updateKycDocuments = `-- name: UpdateKycDocuments :exec
update kyc_records
set
    updated_at = now(),
    identity_doc = $2,
    proof_of_address = $3,
    status = 'pending',
    rejection_reason = null,
    verified_at = null,
    verified_by = null
where
    user_id = $1
`

type UpdateKycDocumentsParams struct {
	UserID         *string
	IdentityDoc    []byte
	ProofOfAddress []byte
}

func (q *Queries) UpdateKycDocuments(ctx context.Context, arg UpdateKycDocumentsParams) error {
	_, err := q.db.Exec(ctx, updateKycDocuments, arg.UserID, arg.IdentityDoc, arg.ProofOfAddress)
	return err
}

const verifyKyc = `-- name: VerifyKyc :exec
update kyc_records
set
    updated_at = now(),
    status = 'verified',
    verified_at = now(),
    verified_by = $2,
    rejection_reason = null,
    risk_profile = $3
where
    user_id = $1
`

type VerifyKycParams struct {
	UserID      *string
	VerifiedBy  *string
	RiskProfile KycRiskProfile
}

func (q *Queries) VerifyKyc(ctx context.Context, arg VerifyKycParams) error {
	_, err := q.db.Exec(ctx, verifyKyc, arg.UserID, arg.VerifiedBy, arg.RiskProfile)
	return err
}
