// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
	decimal "github.com/shopspring/decimal"
)

type AccountProvider string

const (
	AccountProviderCredential  AccountProvider = "credential"
	AccountProviderGoogleOauth AccountProvider = "google-oauth"
)

func (e *AccountProvider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccountProvider(s)
	case string:
		*e = AccountProvider(s)
	default:
		return fmt.Errorf("unsupported scan type for AccountProvider: %T", src)
	}
	return nil
}

type NullAccountProvider struct {
	AccountProvider AccountProvider
	Valid           bool // Valid is true if AccountProvider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccountProvider) Scan(value interface{}) error {
	if value == nil {
		ns.AccountProvider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccountProvider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccountProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccountProvider), nil
}

type ExecutionStatus string

const (
	ExecutionStatusFailed ExecutionStatus = "failed"
	ExecutionStatusFilled ExecutionStatus = "filled"
)

func (e *ExecutionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ExecutionStatus(s)
	case string:
		*e = ExecutionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ExecutionStatus: %T", src)
	}
	return nil
}

type NullExecutionStatus struct {
	ExecutionStatus ExecutionStatus
	Valid           bool // Valid is true if ExecutionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullExecutionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ExecutionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ExecutionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullExecutionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ExecutionStatus), nil
}

type OrderSide string

const (
	OrderSideSell OrderSide = "sell"
	OrderSideBuy  OrderSide = "buy"
)

func (e *OrderSide) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderSide(s)
	case string:
		*e = OrderSide(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderSide: %T", src)
	}
	return nil
}

type NullOrderSide struct {
	OrderSide OrderSide
	Valid     bool // Valid is true if OrderSide is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderSide) Scan(value interface{}) error {
	if value == nil {
		ns.OrderSide, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderSide.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderSide) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderSide), nil
}

type OrderStatus string

const (
	OrderStatusPending         OrderStatus = "pending"
	OrderStatusSubmitted       OrderStatus = "submitted"
	OrderStatusPartiallyFilled OrderStatus = "partially_filled"
	OrderStatusFilled          OrderStatus = "filled"
	OrderStatusCancelled       OrderStatus = "cancelled"
	OrderStatusRejected        OrderStatus = "rejected"
	OrderStatusExpired         OrderStatus = "expired"
)

func (e *OrderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderStatus(s)
	case string:
		*e = OrderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderStatus: %T", src)
	}
	return nil
}

type NullOrderStatus struct {
	OrderStatus OrderStatus
	Valid       bool // Valid is true if OrderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderStatus), nil
}

type OrderType string

const (
	OrderTypeMarket    OrderType = "market"
	OrderTypeLimit     OrderType = "limit"
	OrderTypeStop      OrderType = "stop"
	OrderTypeStopLimit OrderType = "stop_limit"
)

func (e *OrderType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderType(s)
	case string:
		*e = OrderType(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderType: %T", src)
	}
	return nil
}

type NullOrderType struct {
	OrderType OrderType
	Valid     bool // Valid is true if OrderType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderType) Scan(value interface{}) error {
	if value == nil {
		ns.OrderType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderType), nil
}

type TransactionStatus string

const (
	TransactionStatusProcessing TransactionStatus = "processing"
	TransactionStatusFailed     TransactionStatus = "failed"
	TransactionStatusCancelled  TransactionStatus = "cancelled"
	TransactionStatusCompleted  TransactionStatus = "completed"
)

func (e *TransactionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionStatus(s)
	case string:
		*e = TransactionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionStatus: %T", src)
	}
	return nil
}

type NullTransactionStatus struct {
	TransactionStatus TransactionStatus
	Valid             bool // Valid is true if TransactionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionStatus), nil
}

type WalletType string

const (
	WalletTypeReal    WalletType = "real"
	WalletTypeVirtual WalletType = "virtual"
)

func (e *WalletType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WalletType(s)
	case string:
		*e = WalletType(s)
	default:
		return fmt.Errorf("unsupported scan type for WalletType: %T", src)
	}
	return nil
}

type NullWalletType struct {
	WalletType WalletType
	Valid      bool // Valid is true if WalletType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWalletType) Scan(value interface{}) error {
	if value == nil {
		ns.WalletType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WalletType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWalletType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WalletType), nil
}

type Account struct {
	ID                    string
	AccountID             string
	Provider              AccountProvider
	UserID                string
	AccessToken           *string
	RefreshToken          *string
	IDToken               *string
	AccessTokenExpiresAt  pgtype.Timestamp
	RefreshTokenExpiresAt pgtype.Timestamp
	Scope                 *string
	Password              *string
	CreatedAt             pgtype.Timestamp
	UpdatedAt             pgtype.Timestamp
}

type Order struct {
	UserID           *string
	Symbol           string
	Side             OrderSide
	OrderType        OrderType
	Quantity         decimal.Decimal
	LimitPrice       decimal.NullDecimal
	StopPrice        decimal.NullDecimal
	ID               string
	ClientOrderID    *string
	Status           *OrderStatus
	FilledQuantity   decimal.NullDecimal
	AverageFillPrice decimal.NullDecimal
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	TracingID        string
}

type User struct {
	ID            string
	Name          string
	Email         string
	EmailVerified bool
	Image         *string
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
	Prefs         []byte
}

type WalletSnapshot struct {
	WalletID          string
	OwnerID           *string
	StartingBalance   decimal.Decimal
	CurrentBalance    decimal.Decimal
	TotalTransactions int64
	LastActivityAt    pgtype.Timestamptz
	SnapshotCreatedAt pgtype.Timestamptz
	WalletType        WalletType
}

type WalletTransaction struct {
	ID               string
	Value            decimal.Decimal
	Src              *string
	Dest             *string
	Intent           *string
	RecordedAt       pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	ExtraData        []byte
	IdempotencyToken string
	DoneBy           *string
	TracingID        string
	Currency         *string
	ExchangeRate     decimal.Decimal
	Status           TransactionStatus
}
