// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package db

import (
	"context"

	decimal "github.com/shopspring/decimal"
)

const applyOrderFill = `-- name: ApplyOrderFill :exec
UPDATE orders
SET
    filled_quantity = filled_quantity + $1,
    status = (
        CASE
            WHEN filled_quantity + $1 >= quantity THEN 'filled'
            ELSE 'partially_filled'
        END
    )::order_status,
    updated_at = now()
WHERE
    id = $2
    AND status IN ('submitted', 'partially_filled')
`

type ApplyOrderFillParams struct {
	FilledQuantity decimal.NullDecimal
	ID             string
}

func (q *Queries) ApplyOrderFill(ctx context.Context, arg ApplyOrderFillParams) error {
	_, err := q.db.Exec(ctx, applyOrderFill, arg.FilledQuantity, arg.ID)
	return err
}

const createExecution = `-- name: CreateExecution :exec
insert into
    executions (
        id,
        "order",
        price,
        quantity,
        order_side,
        order_status,
        "order_type",
        symbol,
        "user",
        fee_currency,
        fee_rate,
        fee_amount,
        tracing_id,
        exec_status
    )
values
    (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12,
        $13,
        $14
    )
`

type CreateExecutionParams struct {
	ID          string
	Order       string
	Price       decimal.Decimal
	Quantity    decimal.Decimal
	OrderSide   OrderSide
	OrderStatus OrderStatus
	OrderType   OrderType
	Symbol      string
	User        *string
	FeeCurrency string
	FeeRate     decimal.Decimal
	FeeAmount   decimal.Decimal
	TracingID   string
	ExecStatus  ExecutionStatus
}

func (q *Queries) CreateExecution(ctx context.Context, arg CreateExecutionParams) error {
	_, err := q.db.Exec(ctx, createExecution,
		arg.ID,
		arg.Order,
		arg.Price,
		arg.Quantity,
		arg.OrderSide,
		arg.OrderStatus,
		arg.OrderType,
		arg.Symbol,
		arg.User,
		arg.FeeCurrency,
		arg.FeeRate,
		arg.FeeAmount,
		arg.TracingID,
		arg.ExecStatus,
	)
	return err
}

const findOrderById = `-- name: FindOrderById :one
select
    user_id, symbol, side, order_type, quantity, limit_price, stop_price, id, client_order_id, status, filled_quantity, average_fill_price, created_at, updated_at, tracing_id
from
    orders
where
    id = $1
`

func (q *Queries) FindOrderById(ctx context.Context, id string) (Order, error) {
	row := q.db.QueryRow(ctx, findOrderById, id)
	var i Order
	err := row.Scan(
		&i.UserID,
		&i.Symbol,
		&i.Side,
		&i.OrderType,
		&i.Quantity,
		&i.LimitPrice,
		&i.StopPrice,
		&i.ID,
		&i.ClientOrderID,
		&i.Status,
		&i.FilledQuantity,
		&i.AverageFillPrice,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TracingID,
	)
	return i, err
}

const getOrders = `-- name: GetOrders :many
select
    user_id, symbol, side, order_type, quantity, limit_price, stop_price, id, client_order_id, status, filled_quantity, average_fill_price, created_at, updated_at, tracing_id
from
    orders
where
    id > $1
order by
    id
limit
    $2
`

type GetOrdersParams struct {
	ID    string
	Limit int32
}

func (q *Queries) GetOrders(ctx context.Context, arg GetOrdersParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, getOrders, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.UserID,
			&i.Symbol,
			&i.Side,
			&i.OrderType,
			&i.Quantity,
			&i.LimitPrice,
			&i.StopPrice,
			&i.ID,
			&i.ClientOrderID,
			&i.Status,
			&i.FilledQuantity,
			&i.AverageFillPrice,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TracingID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const orderExistsById = `-- name: OrderExistsById :one
select
    exists (
        select
            1
        from
            orders
        where
            id = $1
    )
`

func (q *Queries) OrderExistsById(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, orderExistsById, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const placeOrder = `-- name: PlaceOrder :exec
INSERT INTO
    orders (
        id,
        user_id,
        symbol,
        side,
        order_type,
        quantity,
        limit_price,
        stop_price,
        client_order_id,
        average_fill_price
    )
VALUES
    ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type PlaceOrderParams struct {
	ID               string
	UserID           *string
	Symbol           string
	Side             OrderSide
	OrderType        OrderType
	Quantity         decimal.Decimal
	LimitPrice       decimal.NullDecimal
	StopPrice        decimal.NullDecimal
	ClientOrderID    *string
	AverageFillPrice decimal.NullDecimal
}

func (q *Queries) PlaceOrder(ctx context.Context, arg PlaceOrderParams) error {
	_, err := q.db.Exec(ctx, placeOrder,
		arg.ID,
		arg.UserID,
		arg.Symbol,
		arg.Side,
		arg.OrderType,
		arg.Quantity,
		arg.LimitPrice,
		arg.StopPrice,
		arg.ClientOrderID,
		arg.AverageFillPrice,
	)
	return err
}
