// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package db

import (
	"context"

	decimal "github.com/shopspring/decimal"
)

const applyOrderFill = `-- name: ApplyOrderFill :exec
UPDATE orders
SET
    filled_quantity = filled_quantity + $1,
    status = (
        CASE
            WHEN filled_quantity + $1 >= quantity THEN 'filled'
            ELSE 'partially_filled'
        END
    )::order_status,
    updated_at = now()
WHERE
    id = $2
    AND status IN ('submitted', 'partially_filled')
`

type ApplyOrderFillParams struct {
	FilledQuantity decimal.NullDecimal
	ID             string
}

func (q *Queries) ApplyOrderFill(ctx context.Context, arg ApplyOrderFillParams) error {
	_, err := q.db.Exec(ctx, applyOrderFill, arg.FilledQuantity, arg.ID)
	return err
}

const placeOrder = `-- name: PlaceOrder :one
INSERT INTO
    orders (
        id,
        user_id,
        symbol,
        side,
        order_type,
        quantity,
        limit_price,
        stop_price,
        client_order_id,
        average_fill_price
    )
VALUES
    ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING
    id
`

type PlaceOrderParams struct {
	ID               string
	UserID           *string
	Symbol           string
	Side             OrderSide
	OrderType        OrderType
	Quantity         decimal.Decimal
	LimitPrice       decimal.NullDecimal
	StopPrice        decimal.NullDecimal
	ClientOrderID    *string
	AverageFillPrice decimal.NullDecimal
}

func (q *Queries) PlaceOrder(ctx context.Context, arg PlaceOrderParams) (string, error) {
	row := q.db.QueryRow(ctx, placeOrder,
		arg.ID,
		arg.UserID,
		arg.Symbol,
		arg.Side,
		arg.OrderType,
		arg.Quantity,
		arg.LimitPrice,
		arg.StopPrice,
		arg.ClientOrderID,
		arg.AverageFillPrice,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}
