// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package db

import (
	"context"
)

const updateUserPrefs = `-- name: UpdateUserPrefs :exec
update "user"
set
    prefs = $1,
    updated_at = now()
where
    id = $2
`

type UpdateUserPrefsParams struct {
	Prefs []byte
	ID    string
}

func (q *Queries) UpdateUserPrefs(ctx context.Context, arg UpdateUserPrefsParams) error {
	_, err := q.db.Exec(ctx, updateUserPrefs, arg.Prefs, arg.ID)
	return err
}
