// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wallet.sql

package db

import (
	"context"

	decimal "github.com/shopspring/decimal"
)

const createRealWallet = `-- name: CreateRealWallet :exec
insert into
    wallets (id, "owner", starting_balance)
values
    ($1, $2, $3)
`

type CreateRealWalletParams struct {
	ID              string
	Owner           *string
	StartingBalance decimal.NullDecimal
}

func (q *Queries) CreateRealWallet(ctx context.Context, arg CreateRealWalletParams) error {
	_, err := q.db.Exec(ctx, createRealWallet, arg.ID, arg.Owner, arg.StartingBalance)
	return err
}

const createVirtualWallet = `-- name: CreateVirtualWallet :exec
insert into
    wallets ("type", id, "owner", starting_balance)
values
    ('virtual', $1, $2, $3)
`

type CreateVirtualWalletParams struct {
	ID              string
	Owner           *string
	StartingBalance decimal.NullDecimal
}

func (q *Queries) CreateVirtualWallet(ctx context.Context, arg CreateVirtualWalletParams) error {
	_, err := q.db.Exec(ctx, createVirtualWallet, arg.ID, arg.Owner, arg.StartingBalance)
	return err
}

const findWalletSnapshotByOwnerId = `-- name: FindWalletSnapshotByOwnerId :one
SELECT
    wallet_id, owner_id, starting_balance, current_balance, total_transactions, last_activity_at, snapshot_created_at, wallet_type
FROM
    wallet_snapshots
WHERE
    owner_id = $1
LIMIT
    1
`

func (q *Queries) FindWalletSnapshotByOwnerId(ctx context.Context, ownerID *string) (WalletSnapshot, error) {
	row := q.db.QueryRow(ctx, findWalletSnapshotByOwnerId, ownerID)
	var i WalletSnapshot
	err := row.Scan(
		&i.WalletID,
		&i.OwnerID,
		&i.StartingBalance,
		&i.CurrentBalance,
		&i.TotalTransactions,
		&i.LastActivityAt,
		&i.SnapshotCreatedAt,
		&i.WalletType,
	)
	return i, err
}

const userHasWallet = `-- name: UserHasWallet :one
select
    exists (
        select
            1
        from
            wallets
        where
            "owner" = $1
            and "type" = $2
    )
`

type UserHasWalletParams struct {
	Owner *string
	Type  WalletType
}

func (q *Queries) UserHasWallet(ctx context.Context, arg UserHasWalletParams) (bool, error) {
	row := q.db.QueryRow(ctx, userHasWallet, arg.Owner, arg.Type)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
