// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wallet.sql

package db

import (
	"context"
)

const findWalletSnapshotByOwnerId = `-- name: FindWalletSnapshotByOwnerId :one
SELECT
    wallet_id, owner_id, starting_balance, current_balance, total_transactions, last_activity_at, snapshot_created_at
FROM
    wallet_snapshots
WHERE
    owner_id = $1
LIMIT
    1
`

func (q *Queries) FindWalletSnapshotByOwnerId(ctx context.Context, ownerID *string) (WalletSnapshot, error) {
	row := q.db.QueryRow(ctx, findWalletSnapshotByOwnerId, ownerID)
	var i WalletSnapshot
	err := row.Scan(
		&i.WalletID,
		&i.OwnerID,
		&i.StartingBalance,
		&i.CurrentBalance,
		&i.TotalTransactions,
		&i.LastActivityAt,
		&i.SnapshotCreatedAt,
	)
	return i, err
}
