package matching

import (
	"context"
	"fmt"

	"github.com/brinestone/mogtrade/infra/db"
	"github.com/shopspring/decimal"
)

// AddOrderParams holds the data needed to create and match an order.
// The order ID (ULID) is expected to be generated by the application layer
// and passed in if needed; this struct focuses on the order characteristics.
type AddOrderParams struct {
	// Symbol is the trading pair, e.g. "BTCUSDT".
	Symbol string
	// Side is buy or sell.
	Side string // "buy" or "sell" - kept as string per the "string-only" approach
	// Type is market, limit, stop, stop_limit, etc.
	Type string // "market", "limit", "stop", "stop_limit"
	// Quantity is the order size.
	Quantity decimal.Decimal
	// Price is the limit price; nil for market orders.
	Price *decimal.Decimal
	// UserID is the ID of the user placing the order.
	UserID string
	// OrderID is the unique identifier for the order (ULID string).
	// If empty, the caller should generate one; the matching engine
	// only treats it as a string key.
	OrderID string
}

// AddOrder creates an order and attempts immediate matching.
// The matching engine focuses on order book logic and trade execution.
// It returns the execution trace IDs that resulted from the match.
// Wallet debit/credit is handled by the caller/settlement layer.
func AddOrder(ctx context.Context, params AddOrderParams) ([]string, error) {
	// TODO(implementation):
	// 1. Persist the order in the orders table using params.OrderID.
	// 2. Attempt immediate matching against the opposite‑side book.
	// 3. For each trade, insert a row into the `executions` table
//    with a tracing_id and update counterparties' wallet snapshots via the settlement layer.
// 4. Return the resulting execution trace IDs (may be empty if no trade occurred).

	// Placeholder return – replace with real logic.
	return nil, nil
}

// Match attempts to match a given order against the in‑memory order book.
// It returns the execution trace IDs that were created.
// This is the core price‑time‑priority matching algorithm.
func Match(params AddOrderParams) ([]string, error) {
	// TODO: implement price‑time priority matching:
	// • Market orders: immediately match against opposite‑side limit orders at best price
	// • Limit orders: posted to book; cross‑spread triggers market‑order behaviour
	// • Stop/Stop‑Limit: promoted when market price crosses trigger
	// • Partial fills, self‑match prevention, price/time priority FIFO queues
	// • For each trade, insert an executions row with a tracing_id and return the IDs.
	return nil, nil
}

// CancelOrder marks an order as cancelled and removes it from the book.
func CancelOrder(orderID string, userID string) error {
	// TODO: delete/update the order row and remove from the in‑memory book.
	return fmt.Errorf("not implemented: CancelOrder")
}

// GetOrderBook returns the best bid and ask price levels for a symbol.
func GetOrderBook(symbol string) (bids []decimal.Decimal, asks []decimal.Decimal) {
	// TODO: query the in‑memory book and return price levels.
	return nil, nil
}