// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package models

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCredentialAccount = `-- name: CreateCredentialAccount :one
INSERT INTO
    account (
        id,
        issuer,
        account_id,
        provider,
        user_id,
        "password"
    )
VALUES
    ($1, $2, $3, $4, $5, $6)
RETURNING
    id, issuer, account_id, provider, user_id, access_token, refresh_token, id_token, access_token_expires_at, refresh_token_expires_at, scope, password, created_at, updated_at
`

type CreateCredentialAccountParams struct {
	ID        string
	Issuer    string
	AccountID string
	Provider  AccountProvider
	UserID    string
	Password  pgtype.Text
}

func (q *Queries) CreateCredentialAccount(ctx context.Context, arg CreateCredentialAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createCredentialAccount,
		arg.ID,
		arg.Issuer,
		arg.AccountID,
		arg.Provider,
		arg.UserID,
		arg.Password,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Issuer,
		&i.AccountID,
		&i.Provider,
		&i.UserID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.IDToken,
		&i.AccessTokenExpiresAt,
		&i.RefreshTokenExpiresAt,
		&i.Scope,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO
    "user" (id, name, email, image)
VALUES
    ($1, $2, $3, $4)
RETURNING
    id, name, email, email_verified, image, created_at, updated_at
`

type CreateUserParams struct {
	ID    string
	Name  string
	Email string
	Image pgtype.Text
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Image,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Image,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findUserById = `-- name: FindUserById :one
SELECT
    id, name, email, email_verified, image, created_at, updated_at
FROM
    "user"
WHERE
    id = $1
LIMIT
    1
`

func (q *Queries) FindUserById(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, findUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Image,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
